# -*- coding: utf-8 -*-
"""Speech_assgn_task2_Q3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1beEGnhe_aBXFJzJgZE0mMZtguOWTnCbf
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install pyloudnorm
# !pip install pysndfx
# !pip install speechbrain
# !pip install transformers
# !pip install speechbrain.pretrained
# !pip install torchmetrics
# !pip install wandb

import os
from multiprocessing import Process
import subprocess
import glob

import random
import warnings
import tarfile

import numpy as np
import pandas as pd
import pyloudnorm as pyln
import soundfile as sf
import tqdm as tqdm_module
import zipfile

import tqdm.contrib.concurrent
import functools
from pysndfx import AudioEffectsChain

import librosa

import torchaudio
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader
import torchaudio.transforms as T
import torchmetrics

from IPython.display import Audio

import speechbrain as sb
from speechbrain.dataio.dataio import read_audio
from IPython.display import Audio
from speechbrain.inference.separation import SepformerSeparation as separator

from torchmetrics.audio import ScaleInvariantSignalNoiseRatio
from torchmetrics.audio import ScaleInvariantSignalDistortionRatio
import wandb

from google.colab import drive
drive.mount('/content/drive')

! wandb login c07f9b9363b1d2736cf24c01a4747e245909f2cc

!unzip /content/drive/MyDrive/LibriMix.zip

!unzip /content/drive/MyDrive/speech_task2_Q3.zip

!pip install -r ../content/Speech_task2_Q3/extra_requirements.txt

!python /content/Speech_task2_Q3/separation/train.py /content/Speech_task2_Q3/separation/hparams/sepformer.yaml --data_folder /content

